### ISSUE TITLE
Clarifying the license

### ISSUE THREAD

**Issue by JesseTG** [sttz/trimmer#1]
I'm currently developing a game in Unity, and in the coming days I'll need to spruce up my build pipeline.  trimmer looks interesting, but I can't use it if it means I have to release my game's source code wholesale under the GPL.  Is trimmer's code, in any form, linked into builds of a game?  Or does it stay strictly within the editor?  And if the former, when will you have a commercial license available?

**Comment by sttz** [comment]
The original idea was to try dual-licensing with a commercial version in the Asset Store but I since changed my mind. Ideally, I'd want people to easily share options and make it easy for others to just drop them into their projects, using an open license makes more sense for this.

I just pushed some fixes, bumped to version to 1.0.0 and relicensed the project under the MIT License. I still have to update the documentation.

If a build includes any options, the runtime part of Trimmer will be included as well (everything in the Base folder). If you don't include any options, the runtime part will be removed, minus a few pieces of code (BuildInfo and InjectionContainer) that could be used by included features.

Let me know if you have any questions!

**Comment by JesseTG** [comment]
Didn't expect that, but awesome, thank you!  Which parts of the documentation are out of date, so I know not to rely on them dogmatically?

**Comment by JesseTG** [comment]
Oh, you just meant the part referring to the license, now that I think about it.

**Comment by sttz** [comment]
Yeah, my comment was mostly related to the remaining mentions of the GPL.

I updated the docs yesterday, fixed lots of typos and also added a section, hopefully clarifying the terms Options/Features, to the Using Trimmer section. This is currently not really ideal since I get confused myself from time to time. I'd love to make it clearer but haven't been able to come up with a good metaphor that's easier to grasp but also doesn't take away the flexibility.

**Comment by JesseTG** [comment]
If I come up with something while I'm using it, I'll be sure to let you know.
